# Generated by Django 6.0.1 on 2026-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('cod_ean', models.CharField(max_length=50)),
                ('cod_dun', models.CharField(max_length=50)),
                ('cod_sistema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('conteo_01', models.IntegerField()),
                ('conteo_02', models.IntegerField()),
                ('diferencia', models.IntegerField(editable=False)),
            ],
        ),
    ]
