# Generated by Django 6.0.1 on 2026-01-29 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localesGenerales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
