# Generated by Django 6.0.1 on 2026-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localesGenerales', '0002_inventario_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='conteo_01',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='conteo_02',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='diferencia',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
